方法总结: 

* 删除含有缺失值的样本；
* 删除含有缺失值的特征；
* 0填充,平均值, 中位数, 众数填充；
* 基于模型的填充

##  1.删除含有缺失值的样本

## 2.删除含有缺失值的特征

## 3.零值填充,平均值, 中位数, 众数填充

### 3.1 

pd.DataFrame.fillna()

### 3.2 sklearn.SimpleImputer

In [1]:
# Imputer
from sklearn.impute import SimpleImputer, MissingIndicator

In [2]:
# data
import numpy as np
import pandas as pd
import scipy.sparse as sp

data = [[7, 2, 3], [4, np.nan, 6], [10, 5, 9], [6, 5, 8]]
data_array = np.array([[7, 2, 3], [4, np.nan, 6], [10, 5, 9], [6, 5, 8]])
data_sparse = sp.csc_matrix([[1, 2], [0, -1], [8, 4], [9, 4]])
df = pd.DataFrame([["a", "x"], 
                   [np.nan, "y"],
                   ["a", np.nan],
                   ["b", "y"]], dtype="category")

print("=" * 50)
print("=" + " " * 22 + "data" + " " * 22 + "=")
print("=" * 50)
print(data)
print("-" * 50)
print(data_array)
print("-" * 50)
print(data_sparse)
print("-" * 50)
print(df)
print("-" * 50)

=                      data                      =
[[7, 2, 3], [4, nan, 6], [10, 5, 9], [6, 5, 8]]
--------------------------------------------------
[[ 7.  2.  3.]
 [ 4. nan  6.]
 [10.  5.  9.]
 [ 6.  5.  8.]]
--------------------------------------------------
  (0, 0)	1
  (2, 0)	8
  (3, 0)	9
  (0, 1)	2
  (1, 1)	-1
  (2, 1)	4
  (3, 1)	4
--------------------------------------------------
     0    1
0    a    x
1  NaN    y
2    a  NaN
3    b    y
--------------------------------------------------


#### 常数值填充

In [3]:
imp = SimpleImputer(missing_values = np.nan, strategy = "constant", fill_value = 0)
imp.fit_transform(data)

array([[ 7.,  2.,  3.],
       [ 4.,  0.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [4]:
imp = SimpleImputer(missing_values = np.nan, strategy = "constant", fill_value = 0)
imp.fit_transform(data_array)

array([[ 7.,  2.,  3.],
       [ 4.,  0.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [5]:
imp = SimpleImputer(missing_values = -1, strategy = "constant", fill_value = 0)
imp.fit_transform(data_sparse).toarray()

array([[1, 2],
       [0, 0],
       [8, 4],
       [9, 4]], dtype=int64)

#### 特征平均值填充

In [6]:
imp = SimpleImputer(missing_values = np.nan, strategy = "mean")
imp.fit_transform(data)

array([[ 7.,  2.,  3.],
       [ 4.,  4.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [7]:
imp = SimpleImputer(missing_values = np.nan, strategy = "mean")
imp.fit_transform(data_array)

array([[ 7.,  2.,  3.],
       [ 4.,  4.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [8]:
imp = SimpleImputer(missing_values = -1, strategy = "mean")
imp.fit_transform(data_sparse).toarray()

array([[1.        , 2.        ],
       [0.        , 3.33333333],
       [8.        , 4.        ],
       [9.        , 4.        ]])

#### 特征中位数填充

In [9]:
imp = SimpleImputer(missing_values = np.nan, strategy = "median")
imp.fit_transform(data)

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [10]:
imp = SimpleImputer(missing_values = np.nan, strategy = "median")
imp.fit_transform(data_array)

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [11]:
imp = SimpleImputer(missing_values = -1, strategy = "median")
imp.fit_transform(data_sparse).toarray()

array([[1., 2.],
       [0., 4.],
       [8., 4.],
       [9., 4.]])

#### 众数填充

* 数值型
* 字符型、类别型

In [12]:
imp = SimpleImputer(missing_values = np.nan, strategy = "most_frequent")
imp.fit_transform(data)

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [13]:
imp = SimpleImputer(missing_values = np.nan, strategy = "most_frequent")
imp.fit_transform(data_array)

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10.,  5.,  9.],
       [ 6.,  5.,  8.]])

In [14]:
imp = SimpleImputer(missing_values = -1, strategy = "most_frequent")
imp.fit_transform(data_sparse).toarray()

array([[1, 2],
       [0, 4],
       [8, 4],
       [9, 4]], dtype=int64)

In [15]:
imp = SimpleImputer(missing_values = np.nan, strategy = "most_frequent")
imp.fit_transform(df)

array([['a', 'x'],
       ['a', 'y'],
       ['a', 'y'],
       ['b', 'y']], dtype=object)

## 4.基于模型的填充